Add detector for uint comparisons to greater than 0
crytic/slither pull request #1392
Opened 2022-10-01 19:36 UTC by cre-mer

2022-10-01 19:37 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/crytic/slither?pullRequest=1392) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/crytic/slither?pullRequest=1392) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/crytic/slither?pullRequest=1392) it.</sub>

2022-11-04 17:43 UTC, 0xalpharush commented
I think this would emit false positives unless it considers compiler version and settings. For example, these operations result in the same bytecode if solc 0.8.17 is used with optimizations enabled.

2022-11-04 17:48 UTC, 0xalpharush requested changes
Please filter results based on solc version and compiler optimization configurations and document the heuristic in the wiki.

2022-11-04 17:48 UTC, 0xalpharush commented on slither/detectors/operations/comparing_uint_gt_zero.py
> +    WIKI_DESCRIPTION = "uints are either 0 or greater. Comparing it different than 0 has the same effect but uses less gas."
Would you add a Solidity snippet here like the other detectors have?

2023-01-12 14:26 UTC, closed without merging

2023-03-09 12:07 UTC, cre-mer commented
This was fixed since the introduction of [tautology or contradiction](https://github.com/crytic/slither/wiki/Detector-Documentation#tautology-or-contradiction). No further work is needed.