Add exceptions for i_ and s_ in the naming-conventions detector
crytic/slither pull request #2125
Opened 2023-09-09 01:44 UTC by dokzai

Hello!

This is my attempt at addressing #2083 with updated test data.

Thanks!

2023-09-15 13:52 UTC, 0xalpharush requested changes

2023-09-15 13:52 UTC, 0xalpharush commented on slither/detectors/naming_convention/naming_convention.py
> +                        correct_naming = True
I think these should also be guarded by a check that ensures they're private/immutable as public variables should still be camel case. If this convention is being used, I think public getters with camel cases are created for internal/private variables with the i_/s_ prefix

2023-09-26 23:52 UTC, devtooligan approved these changes
lgtm

2023-10-12 14:27 UTC, montyly approved these changes

2023-10-12 14:27 UTC, merged